[tool.poetry]
name = "python-boilerplate"
version = "0.1.0"
description = "This repository is a Python boilerplate to use as a fast starter point"
authors = ["Pedro Lopez Mareque <pedro.lopez.mareque@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
mypy = "^1.4.1"
ruff = "^0.0.280"
pytest = "^7.4.0"
pytest-xdist = "^3.3.1"
pytest-watch = "^4.2.0"
doublex = "^1.9.6.1"
expects = "^0.9.0"
doublex-expects = "^0.7.1"

[tool.yapf]
based_on_style = "google"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
